name: Lobby
version: '${project.version}'
main: de.korzhorz.lobby.Main
api-version: 1.20
commands:
  setlobby:
    description: Set the lobby
    usage: /setlobby
    aliases: [setspawn]
    permission: lobby.setup
  setwarp:
    description: Set a warp
    usage: /setwarp <name> <slot> <displayname>
    permission: lobby.setup
  delwarp:
    description: Delete a warp
    usage: /delwarp <name>
    permission: lobby.setup
